var annotated_dup =
[
    [ "cse335", null, [
      [ "Polygon", "classcse335_1_1_polygon.html", "classcse335_1_1_polygon" ]
    ] ],
    [ "Actor", "class_actor.html", "class_actor" ],
    [ "AnimChannel", "class_anim_channel.html", "class_anim_channel" ],
    [ "AnimChannelAngle", "class_anim_channel_angle.html", "class_anim_channel_angle" ],
    [ "AnimChannelPoint", "class_anim_channel_point.html", "class_anim_channel_point" ],
    [ "CanadianExperienceApp", "class_canadian_experience_app.html", "class_canadian_experience_app" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "Drawable", "class_drawable.html", "class_drawable" ],
    [ "DrawableMachine", "class_drawable_machine.html", "class_drawable_machine" ],
    [ "HaroldFactory", "class_harold_factory.html", "class_harold_factory" ],
    [ "HeadTop", "class_head_top.html", "class_head_top" ],
    [ "ImageDrawable", "class_image_drawable.html", "class_image_drawable" ],
    [ "Instrument", "class_instrument.html", "class_instrument" ],
    [ "Lever", "class_lever.html", "class_lever" ],
    [ "Machine", "class_machine.html", "class_machine" ],
    [ "Machine1Factory", "class_machine1_factory.html", "class_machine1_factory" ],
    [ "Machine2Factory", "class_machine2_factory.html", "class_machine2_factory" ],
    [ "MachineDemoApp", "class_machine_demo_app.html", "class_machine_demo_app" ],
    [ "MachineDialog", "class_machine_dialog.html", "class_machine_dialog" ],
    [ "MachineInterpret", "class_machine_interpret.html", "class_machine_interpret" ],
    [ "MachineStandin", "class_machine_standin.html", "class_machine_standin" ],
    [ "MachineSystem", "class_machine_system.html", "class_machine_system" ],
    [ "MachineSystemActual", "class_machine_system_actual.html", "class_machine_system_actual" ],
    [ "MachineSystemFactory", "class_machine_system_factory.html", "class_machine_system_factory" ],
    [ "MachineSystemIsolator", "class_machine_system_isolator.html", "class_machine_system_isolator" ],
    [ "MainFrame", "class_main_frame.html", "class_main_frame" ],
    [ "Motor", "class_motor.html", "class_motor" ],
    [ "Peg", "class_peg.html", "class_peg" ],
    [ "PegWheel", "class_peg_wheel.html", "class_peg_wheel" ],
    [ "Picture", "class_picture.html", "class_picture" ],
    [ "PictureFactory", "class_picture_factory.html", "class_picture_factory" ],
    [ "PictureObserver", "class_picture_observer.html", "class_picture_observer" ],
    [ "PolyDrawable", "class_poly_drawable.html", "class_poly_drawable" ],
    [ "Pulley", "class_pulley.html", "class_pulley" ],
    [ "RotatedBitmap", "class_rotated_bitmap.html", "class_rotated_bitmap" ],
    [ "Shape", "class_shape.html", "class_shape" ],
    [ "Sink", "class_sink.html", "class_sink" ],
    [ "Source", "class_source.html", "class_source" ],
    [ "SpartyFactory", "class_sparty_factory.html", "class_sparty_factory" ],
    [ "Timeline", "class_timeline.html", "class_timeline" ],
    [ "TimelineDlg", "class_timeline_dlg.html", "class_timeline_dlg" ],
    [ "ViewEdit", "class_view_edit.html", "class_view_edit" ],
    [ "ViewTimeline", "class_view_timeline.html", "class_view_timeline" ],
    [ "Winch", "class_winch.html", "class_winch" ]
];